//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Games.Entities
{
    using System;
    using System.Collections.Generic;
    using System.IO.Packaging;

    public partial class Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int Article { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string equipment { get; set; }
        public int category { get; set; }
        public int manufacturer { get; set; }
        public System.DateTime release_year { get; set; }
        public decimal cost { get; set; }
        public string photo { get; set; }
    
        public virtual Category Category1 { get; set; }
        public virtual Manufacturer Manufacturer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }

        public string CorrectImg
        {
            get
            {
                if (string.IsNullOrEmpty(photo)|| string.IsNullOrWhiteSpace(photo))
                {
                    return "/Resources/no.jpg";
                }
                else
                { 
                    return "/Resources/" + photo; 
                }
            }
        }
        public static string AdminControlsVisibility
        {
            get
            {
                if (App.CurrentUser == null)
                {
                    return "Collapsed";
                }
                else
                {
                    if (App.CurrentUser.role == 1)
                    {
                        return "Visible";
                    }
                    else
                    {
                        return "Collapsed";
                    }
                }
            }
        }
    }
}
